const fs = require("fs");
const path = require("path");

const eventsDir = path.join(__dirname, "../data/events");
const outputFile = path.join(eventsDir, "index.js");

function generateEventIndex() {
  const files = fs.readdirSync(eventsDir);

  const importLines = [];
  const exportLines = [];

  files.forEach((file) => {
    if (file.endsWith(".json")) {
      const id = path.basename(file, ".json"); // "1" aus "1.json"
      importLines.push(`import event${id}Data from './${file}';`);
      exportLines.push(`  "${id}": event${id}Data,`);
    }
  });

  const content = `// Auto-generated by generateEventIndex.js\n\n${importLines.join(
    "\n"
  )}\n\nexport const allEventData = {\n${exportLines.join("\n")}\n};\n`;

  fs.writeFileSync(outputFile, content);
  console.log("✅ Event-Index erfolgreich erstellt!");
}

generateEventIndex();
