const fs = require("fs");
const path = require("path");

const islandsDir = path.join(__dirname, "../data/islands");
const outputFile = path.join(islandsDir, "index.js");

function generateIndex() {
  const files = fs.readdirSync(islandsDir);

  const importLines = [];
  const exportLines = [];

  files.forEach((file) => {
    if (file.endsWith(".json")) {
      const id = path.basename(file, ".json"); // z.B. "1" aus "1.json"
      importLines.push(`import island${id}Data from './${file}';`);
      exportLines.push(`  "${id}": island${id}Data,`);
    }
  });

  const content = `// Auto-generated by generateIslandIndex.js\n\n${importLines.join(
    "\n"
  )}\n\nexport const allBattleData = {\n${exportLines.join("\n")}\n};\n`;

  fs.writeFileSync(outputFile, content);
  console.log("✅ index.js erfolgreich erstellt!");
}

generateIndex();
